languageCode: en-us
title: 39 Alpha Research
baseURL: https://39alpharesearch.org
relativeURLS: true
timeZone: America/Phoenix
disableKinds:
    - taxonomy
    - term
outputs:
    home:
        - html
markup:
    goldmark:
        parser:
            attribute: true
        renderer:
            unsafe: true
    highlight:
        noClasses: false
build:
  cachebusters:
  - source: layouts/.*
    target: css
params:
    github_username: 39alpha
    author:
        name: 39 Alpha Research
        email: 39alpha@39alpharesearch.org
        address:
            mailing:
                222 S. Mill Ave. Suite 800 Office 52

                Tempe, Arizona 85281
    logo:
        url: /images/39alpha.png
    ein: 84-3180111
    legal: /legal
    donations:
        values:
            - 25.00
            - 50.00
            - 75.00
            - 100.00
menu:
    main:
        - identifier: projects
          title: Projects
          url: /team/projects
          weight: 3
#           parent: "Science Mission"
#           weight: 1
#         - identifier: notebooks
#           title: Notebooks
#           url: /notebooks
#           parent: "Science Mission"
#           weight: 2
#         - identifier: data
#           title: Datasets
#           url: /data
#           parent: "Science Mission"
#           weight: 3
#
