languageCode: en-us
title: 39Alpha Research
relativeURLS: true
timeZone: America/Phoenix
markup:
    goldmark:
        parser:
            attribute: true
        renderer:
            unsafe: true
    highlight:
        noClasses: false
params:
    github_username: 39alpha
    author:
        name: 39Alpha Research
        email: 39alpha@39alpharesearch.org
        address:
            mailing:
                2307 S. Rural Road

                Tempe, Arizona 85282
    logo:
        url: /images/39alpha.png
    ein: 84-3180111
    legal: /legal
    donations:
        values:
            - 25.00
            - 50.00
            - 75.00
            - 100.00
# menu:
#     main:
#         - identifier: projects
#           title: Projects
#           url: /projects
#           parent: "Science Mission"
#           weight: 1
#         - identifier: notebooks
#           title: Notebooks
#           url: /notebooks
#           parent: "Science Mission"
#           weight: 2
#         - identifier: data
#           title: Datasets
#           url: /data
#           parent: "Science Mission"
#           weight: 3
#
